title: Potaito's shed
author: Potaito
# email: your-email@domain.com
tagline: Recipe journal from Kaja and Alessandro
description: > # this means to ignore newlines until "show_exerpts:"
  Engineer, roboticist and technology enthusiast.
url: potaito.github.io/
paginate: 20  # Posts per page
timezone: Europe/Zurich  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

show_excerpts: false # set to true to show excerpts on the homepage


#
# Seo plugin
#
social:
  # name: Ben Balter
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:

# Build settings
permalink: :title/
# permalink: /:categories/:title:output_ext
sass:
  sass_dir: css


# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank

exclude:
  - README.md